apiVersion: v2
name: opscart-watcher
description: Read-only Kubernetes operational triage dashboard
type: application
version: 0.2.2
appVersion: "v1.11.0"
home: https://opscart.com
sources:
  - https://github.com/opscart/opscart-k8s-watcher
maintainers:
  - name: Shamsher Khan
    url: https://opscart.com
keywords:
  - kubernetes
  - operations
  - triage
  - dashboard
  - devops
